kind: Deployment
apiVersion: apps/v1
metadata:
  name: mosquitto
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto
  template:
    metadata:
      labels:
        name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
          - containerPort: 1883
          volumeMounts:
          - name: mosquitto-config-file
            mountPath: /mosquitto/config
          - name: mosquitto-pwfile
            mountPath: /mosquitto/config/pwfile
          - name: mosquitto-log
            mountPath: /mosquitto/log
          - name: mosquitto-data
            mountPath: /mosquitto/data
      volumes:
      - name: mosquitto-config-file
        configMap:
          name: mosquitto-config
      - name: mosquitto-pwfile
        secret:
          secretName: mosquitto-pwfile
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data-pvc
      - name: mosquitto-log
        persistentVolumeClaim:
          claimName: mosquitto-log-pvc